import { z } from "zod";

const seoSchema = {
  seoTitle: z.string().trim().optional().or(z.literal("")),
  seoDescription: z.string().trim().optional().or(z.literal("")),
  seoKeywords: z.string().trim().optional().or(z.literal("")),
};

export const cmsSchemas = {
  hero: z.object({
    title: z.string().min(1, "Title is required"),
    subtitle: z.string().optional().or(z.literal("")),
    ctaText: z.string().optional().or(z.literal("")),
    ctaLink: z.string().optional().or(z.literal("")),
    backgroundImage: z.string().optional().or(z.literal("")),
    isPublished: z.boolean().optional(),
    displayOrder: z.number().int().optional(),
    ...seoSchema,
  }),
  about: z.object({
    title: z.string().min(1, "Title is required"),
    content: z.string().min(1, "Content is required"),
    image: z.string().optional().or(z.literal("")),
    isPublished: z.boolean().optional(),
    displayOrder: z.number().int().optional(),
    ...seoSchema,
  }),
  service: z.object({
    title: z.string().min(1, "Title is required"),
    description: z.string().min(1, "Description is required"),
    icon: z.string().optional().or(z.literal("")),
    isPublished: z.boolean().optional(),
    displayOrder: z.number().int().optional(),
    slug: z.string().min(1, "Slug is required"),
    ...seoSchema,
  }),
  portfolio: z.object({
    title: z.string().min(1, "Title is required"),
    description: z.string().min(1, "Description is required"),
    image: z.string().optional().or(z.literal("")),
    category: z.string().optional().or(z.literal("")),
    clientName: z.string().optional().or(z.literal("")),
    projectDate: z.string().optional().or(z.literal("")),
    ctaLink: z.string().optional().or(z.literal("")),
    isPublished: z.boolean().optional(),
    displayOrder: z.number().int().optional(),
    slug: z.string().min(1, "Slug is required"),
    ...seoSchema,
  }),
  testimonial: z.object({
    author: z.string().min(1, "Author name is required"),
    company: z.string().optional().or(z.literal("")),
    role: z.string().optional().or(z.literal("")),
    content: z.string().min(1, "Content is required"),
    image: z.string().optional().or(z.literal("")),
    rating: z.number().int().min(1).max(5).optional(),
    isPublished: z.boolean().optional(),
    displayOrder: z.number().int().optional(),
    slug: z.string().optional().or(z.literal("")),
  }),
  faq: z.object({
    question: z.string().min(1, "Question is required"),
    answer: z.string().min(1, "Answer is required"),
    isPublished: z.boolean().optional(),
    displayOrder: z.number().int().optional(),
    slug: z.string().optional().or(z.literal("")),
  }),
  technology: z.object({
    name: z.string().min(1, "Name is required"),
    category: z.string().optional().or(z.literal("")),
    logo: z.string().optional().or(z.literal("")),
    isPublished: z.boolean().optional(),
    displayOrder: z.number().int().optional(),
    slug: z.string().optional().or(z.literal("")),
  }),
  teamMember: z.object({
    name: z.string().min(1, "Name is required"),
    role: z.string().min(1, "Role is required"),
    bio: z.string().optional().or(z.literal("")),
    image: z.string().optional().or(z.literal("")),
    socialLinks: z.any().optional(),
    isPublished: z.boolean().optional(),
    displayOrder: z.number().int().optional(),
    slug: z.string().optional().or(z.literal("")),
  }),
  siteSetting: z.object({
    logo: z.string().optional().or(z.literal("")),
    companyName: z.string().min(1, "Company Name is required"),
    email: z.string().email("Invalid email format"),
    phone: z.string().optional().or(z.literal("")),
    address: z.string().optional().or(z.literal("")),
    businessHours: z.any().optional(),
    socialLinks: z.any().optional(),
    googleAnalyticsId: z.string().optional().or(z.literal("")),
    metaTitle: z.string().optional().or(z.literal("")),
    metaDescription: z.string().optional().or(z.literal("")),
    openGraphImage: z.string().optional().or(z.literal("")),
    favicon: z.string().optional().or(z.literal("")),
    themeSettings: z.any().optional(),
  }),
  socialLink: z.object({
    platform: z.string().min(1, "Platform is required"),
    url: z.string().url("Must be a valid URL"),
    isPublished: z.boolean().optional(),
    displayOrder: z.number().int().optional(),
    slug: z.string().optional().or(z.literal("")),
  }),
  footer: z.object({
    copyrightText: z.string().min(1, "Copyright Text is required"),
    links: z.any().optional(),
    isPublished: z.boolean().optional(),
    slug: z.string().optional().or(z.literal("")),
  }),
};
